#!/usr/bin/env python3
"""
Generate sitemap.xml from the page registry in pages.py.

Driving it off the same registry the pages are built from means the sitemap
cannot list a page that does not exist, or miss one that does. The host comes
from SITE_URL in build.py, so there is a single place to change the domain.

    python3 tools/make-sitemap.py

Pages excluded from the sitemap (no search value, or not a landing page):
auth screens, the signed-in dashboard, and the 404.
"""

import pathlib
import sys

TOOLS = pathlib.Path(__file__).resolve().parent
ROOT = TOOLS.parent

NOINDEX = {
    'login.html',
    'register.html',
    'forgot-password.html',
    'user-dashboard.html',
    '404.html',
}

PRIORITY = {
    'index.html': '1.0',
    'features.html': '0.9',
    'pricing.html': '0.9',
    'docs.html': '0.9',
    'index-creator.html': '0.8',
    'index-enterprise.html': '0.8',
    'blog.html': '0.8',
    'integrations.html': '0.8',
}

# Reuse build.py's registry and SITE_URL without running its CLI.
ns = {'__file__': str(TOOLS / 'build.py'), '__name__': 'build_import'}
exec(compile((TOOLS / 'build.py').read_text(), 'build.py', 'exec'), ns)
exec((TOOLS / 'pages.py').read_text(), ns)

SITE_URL = ns['SITE_URL']
PAGES = ns['PAGES']


def main(lastmod):
    rows = []
    for filename in sorted(PAGES):
        if filename in NOINDEX:
            continue
        slug = '' if filename == 'index.html' else filename
        rows.append(
            '  <url>\n'
            '    <loc>%s/%s</loc>\n'
            '    <lastmod>%s</lastmod>\n'
            '    <changefreq>%s</changefreq>\n'
            '    <priority>%s</priority>\n'
            '  </url>' % (
                SITE_URL, slug, lastmod,
                'weekly' if filename in ('index.html', 'blog.html', 'changelog.html') else 'monthly',
                PRIORITY.get(filename, '0.7')))

    (ROOT / 'sitemap.xml').write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by tools/make-sitemap.py — do not edit by hand.\n'
        '     Host comes from SITE_URL in tools/build.py. -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + '\n'.join(rows) + '\n</urlset>\n', encoding='utf-8')

    print('sitemap.xml: %d indexable URLs (%d excluded as noindex)'
          % (len(rows), len(NOINDEX)))
    return 0


if __name__ == '__main__':
    # Pass a date explicitly to keep runs reproducible; defaults to today.
    if len(sys.argv) > 1:
        stamp = sys.argv[1]
    else:
        import datetime
        stamp = datetime.date.today().isoformat()
    sys.exit(main(stamp))
